name: Generate Changelog from History

# Only manual trigger
on:
  workflow_dispatch:

jobs:
  generate-history-changelog:
    runs-on: ubuntu-latest

    environment:
      name: BOT_TOKEN  # optional
      
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master  # <-- force checkout of master branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub GitPython
      - name: Generate changelog from history
        run: |
          python tools/changelog/generate_cl_from_history.py
